### ISSUE TITLE
Cannot pip install on Windows

### ISSUE THREAD

**Issue by pllim** [maartenbreddels/ipymaterialui#5]
For some reason, `glue-jupyter` is pulling this package and it fails to install on Windows.

```
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\PL\AppData\Local\Temp\pip-install-l5fbenxu\ipymaterialui\setup.py", line 176, in <module>
      setup(**setup_args)
    File "C:\Users\PL\Miniconda3\envs\py37\lib\site-packages\setuptools\__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\PL\Miniconda3\envs\py37\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\PL\Miniconda3\envs\py37\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\PL\Miniconda3\envs\py37\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\PL\Miniconda3\envs\py37\lib\site-packages\wheel\bdist_wheel.py", line 228, in run
      self.run_command('install')
    File "C:\Users\PL\Miniconda3\envs\py37\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\PL\Miniconda3\envs\py37\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\PL\Miniconda3\envs\py37\lib\site-packages\setuptools\command\install.py", line 61, in run
      return orig.install.run(self)
    File "C:\Users\PL\Miniconda3\envs\py37\lib\distutils\command\install.py", line 557, in run
      self.run_command(cmd_name)
    File "C:\Users\PL\Miniconda3\envs\py37\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\PL\Miniconda3\envs\py37\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\PL\Miniconda3\envs\py37\lib\distutils\command\install_data.py", line 56, in run
      dir = convert_path(f[0])
    File "C:\Users\PL\Miniconda3\envs\py37\lib\distutils\util.py", line 112, in convert_path
      raise ValueError("path '%s' cannot end with '/'" % pathname)
  ValueError: path 'etc/jupyter/nbconfig/notebook.d/' cannot end with '/'
  ----------------------------------------
```

**Comment by maartenbreddels** [comment]
Thanks for the report, we had the same issue with ipyvuetify, indeed windows does not like that trailing slash.

**Comment by maartenbreddels** [comment]
this is fixed in master
